This patch enables complex data transfers based on the following concept. A data is allocated from an arena, and some part of it can be described by a specific layout, a count and a displacement. Thus, the most complex output dependency looks like
A -> B T() [layout = MPI_DOUBLE
            count = 10
            displ = 8]

In MPI terms this will generate a transfer of 10 doubles starting at position 8
(in bytes) from the begining of data A. There is no need for an arena here, it
is clearly defined by the riginal type of A.

Now on the recv side, a similar code will look like:

A <- B T() [type = DEFAULT
            layout = MPI_DOUBLE
            count = 10
            displ = 8]
This input dependency has exacttly the same meaning as above with one significant
exception: if necessary the data for A will be allocated based on the type
attached to the DEFAULT arena.